apiVersion: v1
kind: ReplicationController
metadata:
  namespace: mongo-cluster
  name: mongodb-2-rs1
spec:
  replicas: 1
  selector:
    name: mongodb-2-rs1
  template:
    metadata:
      labels:
        name: mongodb-2-rs1
        db: mongodb
      name: mongodb-2-rs1
    spec:
      containers:
      #- imagePullPolicy: Always
      - image: mongo:latest
        name: mongodb
        args:
         - "mongod"
         - "--smallfiles"
         - "--noprealloc"
         - "--nojournal"
         - "--shardsvr"
         - "--replSet"
         - "rs1" 
         - "--noauth"
         - "--bind_ip_all"
         - "--port"
         - "27017"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: node12-2-nfs
