apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook
spec:
  replicas: 2
  selector:
    name: guestbook
  template:
    metadata:
      labels:
        name: guestbook
      name: guestbook
    spec:
      containers:
      - imagePullPolicy: Always
        image: eu.gcr.io/test-cg/guestbook:meetup-0.1
        name: guestbook
        # Checks when the container is ready.
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        # Checks if the container is still alive.
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080