apiVersion: v1
kind: Service
metadata:
  name: mongodb-3-rs1
  namespace: mongo-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongod
  selector:
    name: mongodb-3-rs1
  type: ClusterIP
