apiVersion: v1
kind: Service
metadata:
  name: mongodb-2-ncfg
  namespace: mongo-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    name: mongodb-2-ncfg
  type: NodePort
