apiVersion: v1
kind: ReplicationController
metadata:
  namespace: #namespace
  name: mongos-#cfgi
spec:
  replicas: 1
  selector:
    name: mongos-#cfgi
  template:
    metadata:
      labels:
        name: mongos-#cfgi
        db: mongodb
      name: mongodb-#cfgi
    spec:
      containers:
      #- imagePullPolicy: Always
      - image: mongo:latest
        name: mongodb
        args:
         - "mongos"
         - "--configdb"
         - "#cfg-ips"
         - "--port"
         - "27017"
         - "--bind_ip_all"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: node21-#cfgi-nfs