apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node12-6-nfs
  namespace: mongo-cluster
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
