apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-data
  namespace: es-cluster
  labels:
    component: elasticsearch
    role: data
spec:
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: amolshinde23/es-cluster:1.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myes_cluster"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_HEAP_SIZE
          value: "1g"
        - name: NUMBER_OF_SHARDS
          value: "2"
        - name: NUMBER_OF_REPLICAS
          value: "1"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
        volumeMounts:
        - name: storage
          mountPath: /data
      imagePullSecrets:
      - name: regsecret
 volumeClaimTemplates:
 - metadata:
     name: storage
     annotations:
       volume.beta.kubernetes.io/storage-class: standard
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 12Gi
