apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  namespace: es-cluster
  labels:
    component: elasticsearch
    role: master
spec:
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: amolshinde23/es-cluster:2.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myes_cluster"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: ES_HEAP_SIZE
          value: "512m"
        - name: NUMBER_OF_SHARDS
          value: "2"
        - name: NUMBER_OF_REPLICAS
          value: "1"
        - name: NUMBER_OF_MASTERS
          value: "2"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - emptyDir: 
          medium: ""
        name: "storage"
  imagePullSecrets:
  - name: regsecret
