apiVersion: v1
kind: Service
metadata:
  name: mongos-2
  namespace: mongo-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    name: mongos-2
  type: ClusterIP