apiVersion: v1
kind: Service
metadata:
  name: mongodb-1-rs2
  namespace: mongo-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    name: mongodb-1-rs2
  type: ClusterIP
