apiVersion: v1
kind: ReplicationController
metadata:
  namespace: mongo-cluster
  name: mongodb-2-ncfg
spec:
  replicas: 1
  selector:
    name: mongodb-2-ncfg
  template:
    metadata:
      labels:
        name: mongodb-2-ncfg
        db: mongodb
      name: mongodb-2-ncfg
    spec:
      containers:
      #- imagePullPolicy: Always
      - image: mongo:latest
        name: mongodb
        args:
         - "mongod"
         - "--smallfiles"
         - "--noprealloc"
         - "--configsvr"
         - "--replSet"
         - "ncfg"
         - "--noauth"
         - "--port"
         - "27017"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: node21-2-nfs
