apiVersion: v1
kind: PersistentVolume
metadata:
  name: node21-4-nfs
  namespace: mongo-cluster
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.102.21
    path: "/mnt/k8s/nfs4/"
